package com.rest.gymapp.controller;

import com.rest.gymapp.dto.request.trainer.TrainerActivationRequest;
import com.rest.gymapp.dto.request.trainer.TrainerRegistrationRequest;
import com.rest.gymapp.dto.request.trainer.TrainerUpdateRequest;
import com.rest.gymapp.dto.response.RegistrationResponse;
import com.rest.gymapp.dto.response.trainer.TrainerProfileResponse;
import com.rest.gymapp.dto.response.trainer.TrainerUpdateResponse;
import com.rest.gymapp.dto.response.training.TrainingResponseForTrainer;
import com.rest.gymapp.service.TrainerService;
import io.swagger.annotations.*;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

@RestController
@RequiredArgsConstructor
@RequestMapping("/api/trainers")
@Api(tags = "Trainer Management")
public class TrainerController {

    private final TrainerService trainerService;
    private static final Logger logger = LoggerFactory.getLogger(TrainerService.class);

    @ApiOperation(value = "Register a new trainer", notes = "Creates a trainer profile with autogenerated credentials.")
    @ApiResponses({
            @ApiResponse(code = 201, message = "Trainer registered successfully"),
            @ApiResponse(code = 400, message = "Validation failed")
    })
    @PostMapping("/register")
    public ResponseEntity<RegistrationResponse> registerTrainer(
            @Valid @RequestBody TrainerRegistrationRequest req) {

        String transactionId = UUID.randomUUID().toString();
        logger.info("[{}] POST /api/trainers/register called with payload: {}", transactionId, req);

        RegistrationResponse response = trainerService.createTrainerProfile(req, transactionId);

        logger.info("[{}] Trainer registered successfully: {}", transactionId, response.username());
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    @ApiOperation(value = "Get trainer profile", notes = "Fetches trainer profile details by username.")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Profile fetched successfully"),
            @ApiResponse(code = 404, message = "Trainer not found"),
            @ApiResponse(code = 401, message = "Invalid credentials")
    })
    @GetMapping("/trainer")
    public ResponseEntity<TrainerProfileResponse> getTrainer(
            @ApiParam(value = "Trainer username", required = true) @RequestHeader String username,
            @ApiParam(value = "Trainer password", required = true) @RequestHeader String password) {

        String transactionId = UUID.randomUUID().toString();
        logger.info("[{}] GET /api/trainers/trainer called for user: {}", transactionId, username);

        TrainerProfileResponse response = trainerService.getTrainerByUsername(username, password, transactionId);

        logger.info("[{}] Trainer profile retrieved successfully for username={}", transactionId, username);
        return ResponseEntity.ok(response);
    }

    @ApiOperation(value = "Update trainer profile", notes = "Updates trainer details like name and specialization.")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Profile updated successfully"),
            @ApiResponse(code = 404, message = "Trainer not found")
    })
    @PutMapping("/update-trainer")
    public ResponseEntity<TrainerUpdateResponse> updateTrainer(
            @Valid @RequestBody TrainerUpdateRequest req,
            @ApiParam(value = "Trainee username", required = true) @RequestHeader String username,
            @ApiParam(value = "Trainee password", required = true) @RequestHeader String password) {

        String transactionId = UUID.randomUUID().toString();
        logger.info("[{}] PUT /api/trainers/update-trainer called for username={} with payload={}", transactionId, username, req);

        TrainerUpdateResponse response = trainerService.updateTrainerProfile(req, username, password, transactionId);

        logger.info("[{}] Trainer profile updated successfully for username={}", transactionId, username);
        return ResponseEntity.ok(response);

    }

    @ApiOperation(value = "Get trainer trainings", notes = "Fetches trainings by date range and trainee name as well as other criteria.")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Trainings fetched successfully"),
            @ApiResponse(code = 404, message = "No trainings found")
    })
    @GetMapping("/trainer/trainings")
    public ResponseEntity<List<TrainingResponseForTrainer>> findTrainerTrainings(
            @ApiParam(value = "Trainer username", required = true) @RequestHeader String username,
            @ApiParam(value = "Trainer password", required = true) @RequestHeader String password,
            @ApiParam(value = "Start date (optional)") @RequestParam(required = false) LocalDate fromDate,
            @ApiParam(value = "End date (optional)") @RequestParam(required = false) LocalDate toDate,
            @ApiParam(value = "Trainee name (optional)") @RequestParam(required = false) String traineeName
    ) {
        String transactionId = UUID.randomUUID().toString();
        logger.info("[{}] GET /api/trainers/trainer/trainings called for username={}, fromDate={}, toDate={}, traineeName={}",
                transactionId, username, fromDate, toDate, traineeName);

        List<TrainingResponseForTrainer> response =
                trainerService.findTrainerTrainingsByCriteria(username, password, fromDate, toDate, traineeName, transactionId);

        logger.info("[{}] Found {} trainings for trainer={}", transactionId, response.size(), username);
        return ResponseEntity.ok(response);
    }

    @ApiOperation(value = "Change trainer activation status", notes = "Activates or deactivates the trainer profile.")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Status updated successfully"),
            @ApiResponse(code = 404, message = "Trainer not found")
    })
    @PatchMapping("/trainer/activate-deactivate")
    public ResponseEntity<?> changeActivationStatus(
            @Valid @RequestBody TrainerActivationRequest req,
            @ApiParam(value = "Trainee username", required = true) @RequestHeader String username,
            @ApiParam(value = "Trainee password", required = true) @RequestHeader String password) {

        String transactionId = UUID.randomUUID().toString();
        logger.info("[{}] PATCH /api/trainers/trainer/activate-deactivate called: {}", transactionId, req);

        trainerService.activateDeactivateTrainer(req, username, password, transactionId);

        logger.info("[{}] PATCH /api/trainers/trainer/activate-deactivate response: success", transactionId);

        return ResponseEntity.status(HttpStatus.OK).build();
    }
}
