package com.gymapp.controller;

import com.gymapp.dto.request.trainer.TrainerActivationRequest;
import com.gymapp.dto.request.trainer.TrainerRegistrationRequest;
import com.gymapp.dto.request.trainer.TrainerUpdateRequest;
import com.gymapp.dto.response.RegistrationResponse;
import com.gymapp.dto.response.trainer.TrainerProfileResponse;
import com.gymapp.dto.response.trainer.TrainerUpdateResponse;
import com.gymapp.dto.response.training.TrainingResponseForTrainer;
import com.gymapp.service.TrainerService;
import io.swagger.annotations.*;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

@RestController
@RequiredArgsConstructor
@RequestMapping("/api/trainers")
@Api(tags = "Trainer Management")
public class TrainerController {

    private final TrainerService trainerService;
    private static final Logger logger = LoggerFactory.getLogger(TrainerController.class);

    @ApiOperation(value = "Register a new trainer", notes = "Creates a trainer profile with autogenerated credentials.")
    @ApiResponses({
            @ApiResponse(code = 201, message = "Trainer registered successfully"),
            @ApiResponse(code = 400, message = "Validation failed")
    })
    @PostMapping
    public ResponseEntity<RegistrationResponse> registerTrainer(
            @Valid @RequestBody TrainerRegistrationRequest req) {

        String transactionId = UUID.randomUUID().toString();
        logger.info("[{}] POST /api/trainers/registration called with payload: {}", transactionId, req);

        RegistrationResponse response = trainerService.createTrainerProfile(req, transactionId);

        logger.info("[{}] Trainer registered successfully: {}", transactionId, response.username());
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    @ApiOperation(value = "Get trainer profile", notes = "Fetches trainer profile details by username.")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Profile fetched successfully"),
            @ApiResponse(code = 404, message = "Trainer not found"),
            @ApiResponse(code = 401, message = "Invalid credentials")
    })
    @GetMapping("/{id}")
    public ResponseEntity<TrainerProfileResponse> getTrainer(
            @ApiParam(value = "Trainer id", required = true) @PathVariable Long id) {

        String transactionId = UUID.randomUUID().toString();
        logger.info("[{}] GET /api/trainers/{} called for user", transactionId, id);

        TrainerProfileResponse response = trainerService.getTrainerById(id, transactionId);

        logger.info("[{}] Trainer profile retrieved successfully for username={}", transactionId, id);
        return ResponseEntity.ok(response);
    }

    @ApiOperation(value = "Update trainer profile", notes = "Updates trainer details like name and specialization.")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Profile updated successfully"),
            @ApiResponse(code = 404, message = "Trainer not found")
    })
    @PutMapping("/{id}")
    public ResponseEntity<TrainerUpdateResponse> updateTrainer(
            @Valid @RequestBody TrainerUpdateRequest req,
            @ApiParam(value = "Trainee username", required = true) @PathVariable Long id) {

        String transactionId = UUID.randomUUID().toString();
        logger.info("[{}] PUT /api/trainers/{} called for trainer={} with payload={}", transactionId, id, id, req);

        TrainerUpdateResponse response = trainerService.updateTrainerProfile(id, req, transactionId);

        logger.info("[{}] Trainer profile updated successfully for trainer={}", transactionId, id);
        return ResponseEntity.ok(response);
    }

    @ApiOperation(value = "Get trainer trainings", notes = "Fetches trainings by date range and trainee name as well as other criteria.")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Trainings fetched successfully"),
            @ApiResponse(code = 404, message = "No trainings found")
    })
    @GetMapping("/{id}/trainings")
    public ResponseEntity<List<TrainingResponseForTrainer>> findTrainerTrainings(
            @ApiParam(value = "Trainer id", required = true) @PathVariable Long id,
            @ApiParam(value = "Start date (optional)") @RequestParam(required = false) LocalDate fromDate,
            @ApiParam(value = "End date (optional)") @RequestParam(required = false) LocalDate toDate,
            @ApiParam(value = "Trainee name (optional)") @RequestParam(required = false) String traineeName
    ) {
        String transactionId = UUID.randomUUID().toString();
        logger.info("[{}] GET /api/trainers/{}/trainings called for trainer={}, fromDate={}, toDate={}, traineeName={}",
                transactionId, id, id, fromDate, toDate, traineeName);

        List<TrainingResponseForTrainer> response =
                trainerService.findTrainerTrainingsByCriteria(id, fromDate, toDate, traineeName, transactionId);

        logger.info("[{}] Found {} trainings for trainer={}", transactionId, response.size(), id);
        return ResponseEntity.ok(response);
    }

    @ApiOperation(value = "Change trainer activation status", notes = "Activates or deactivates the trainer profile.")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Status updated successfully"),
            @ApiResponse(code = 404, message = "Trainer not found")
    })
    @PatchMapping("/{id}/activation")
    public ResponseEntity<?> changeActivationStatus(
            @Valid @RequestBody TrainerActivationRequest req,
            @ApiParam(value = "Trainer id", required = true) @PathVariable Long id) {

        String transactionId = UUID.randomUUID().toString();
        logger.info("[{}] PATCH /api/trainers/{}/activation called: {}", transactionId, id, req);

        trainerService.activateDeactivateTrainer(id, req, transactionId);

        logger.info("[{}] PATCH /api/trainers/{}/activation response: success", transactionId, id);

        return ResponseEntity.status(HttpStatus.OK).build();
    }
}
